application: ramesh7128
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /img
  static_dir: img

- url: /.*
  script: blogit.app

libraries:
- name: jinja2                                                                  
  version: latest
